# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Accountant' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Accountant
    pod 'RealmSwift'
    pod 'NeuKit'
    pod 'EMTNeumorphicView'
    pod 'Firebase/Analytics'
    pod 'Firebase/AdMob'
    pod 'Google-Mobile-Ads-SDK'
    pod 'Gecco'

  target 'AccountantTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AccountantUITests' do
    # Pods for testing
  end

end
